# Generated by Django 4.0.3 on 2022-03-15 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('institution', models.CharField(max_length=200, verbose_name='Institución')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='author_manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_autor', models.IntegerField(verbose_name='Posición del autor en este manuscrito')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.author')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('volume', models.IntegerField(verbose_name='Volumen')),
                ('number', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_largo', models.CharField(max_length=300)),
                ('titulo_corto', models.CharField(max_length=200)),
                ('documento_manuscrito', models.FileField(upload_to='uploads/manuscrito')),
                ('documento_lista_cotejo', models.FileField(upload_to='uploads/cotejo')),
                ('documento_originalidad', models.FileField(upload_to='uploads/originalidad')),
                ('documento_carta_presentacion', models.FileField(upload_to='uploads/presentacion')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha de recepción')),
                ('fecha_aceptado', models.DateField(verbose_name='Fecha de aceptación')),
                ('autores', models.ManyToManyField(blank=True, through='revista.author_manuscript', to='revista.author')),
                ('edicion', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='revista.edition', verbose_name='Edición')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Revisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='revisor_manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha de recepción por el revisor')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de devolución por el revisor')),
                ('manuscrito_a_revisar', models.FileField(upload_to='uploads/manuscritorevisar')),
                ('manuscrito_revisado', models.FileField(upload_to='uploads/manuscritorevisado')),
                ('lista_cotejo', models.FileField(upload_to='uploads/revisorlistacotejo')),
                ('manuscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.manuscript')),
                ('recomendacion', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='revista.status', verbose_name='Recomendación')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.revisor')),
            ],
        ),
        migrations.CreateModel(
            name='revisor_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=300)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.area')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.revisor')),
            ],
        ),
        migrations.AddField(
            model_name='revisor',
            name='areas',
            field=models.ManyToManyField(blank=True, through='revista.revisor_area', to='revista.area'),
        ),
        migrations.AddField(
            model_name='revisor',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='revisores',
            field=models.ManyToManyField(blank=True, through='revista.revisor_manuscript', to='revista.revisor'),
        ),
        migrations.AddField(
            model_name='author_manuscript',
            name='manuscrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista.manuscript'),
        ),
        migrations.AddField(
            model_name='author',
            name='profesion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='revista.profession', verbose_name='Profesión'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
